### ISSUE TITLE
Upcoming crash expecting algorithm

### ISSUE THREAD

**Issue by BitMaster001** [TI-Cpp/main-engine-algo#4]
A new crash expecting algorithm is in the progress of development.
Anybody who have any ideas about crash expecting algorithm, please leave a note.

**Comment by BitMaster001** [comment]
Famous military investors announced an investment plan on rocket development in XXX group. Also that group hired some talent military field software developers. Their exact salary is secret but range is around 500K.

**Comment by aifeelit** [comment]
lol... 500K?
I think it's 1200K!  lol.. xP
