### ISSUE TITLE
Research on the Rasjinskaya-Kovan Multi-Dimentional Safety Guarantee Algorithm (RKMDSGA)

### ISSUE THREAD

**Issue by BitMaster001** [TI-Cpp/main-engine-algo#6]
### One critical bug in the RKMDSG Algorithm

At step 932:
...
pThoda = sin(pThido) ^ arcsin(log(PI*2.31)) * (sqrt(n3S56 ^ (nTHI - fG45)))
...

**Comment by aifeelit** [comment]
pThoda = sin(pThido) ^ arcsin(log(PI*2.31)) * (sqrt(n3S56 ^ (nTHI - fG45)))

In this formula 2.31 is changed to be 2.31112 (to be more accurate)

**Comment by aifeelit** [comment]
Then it's fine.
